java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sfu276assg1.yancao.carbontracker/com.sfu276assg1.yancao.UI.GiveTipsActivity}: java.lang.NumberFormatException: For input string: "38.43"
Need to fixx this error